project/news/urls.py
from django.urls import path
# Импортируем созданное нами представление
from .views import (PostView, PostCategoryView, CommentView, ArticleView, SearchView, create_post,
                    PostUpdate, PostDelete, PostCreate, subscriptions, IndexView)
from django.views.decorators.cache import cache_page
from django.contrib import admin


urlpatterns = [
   # path — означает путь.
   # В данном случае путь ко всем товарам у нас останется пустым,
   # чуть позже станет ясно почему.
   # Т.к. наше объявленное представление является классом,
   # а Django ожидает функцию, нам надо представить этот класс в виде view.
   # Для этого вызываем метод as_view.
   path('', PostView.as_view(), name='post_list'),
   # pk — это первичный ключ товара, который будет выводиться у нас в шаблон
   # int — указывает на то, что принимаются только целочисленные значения
   path('<int:pk>', PostCategoryView.as_view()),
   path('comment<int:pk>', CommentView.as_view()),
   path('article/<int:pk>', ArticleView.as_view()),
   path('search', SearchView.as_view()),
   path('createfunc/', create_post),
   path('post/<int:pk>/update/', PostUpdate.as_view(), name='post_update'),
   path('post/<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
   path('create/', PostCreate.as_view(), name='post_create'),
   path('post/<int:pk>/', cache_page(60 * 1)(PostView.as_view()), name='post_detail'),
   path('subscriptions/', subscriptions, name='subscriptions'),
   path('hello/', IndexView.as_view()),
]

project/project/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
   path('admin/', admin.site.urls),
   path("accounts/", include("allauth.urls")),
   path('news/', include('news.urls')),
   path("accounts/", include("django.contrib.auth.urls")),


]

project/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.core.validators import MinValueValidator
from django.urls import reverse


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)
    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.ratingAuthor = pRat * 3 + cRat
        self.save()


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name

class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = (
        (NEWS, "новость"),
        (ARTICLE, "статья"),
    )
    categoryType = models.CharField(max_length=2,choices=CATEGORY_CHOICES, default = ARTICLE)
    category = models.ForeignKey(Category,  on_delete=models.CASCADE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    # postCategory = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()
    def dislike(self):
        self.rating -= 1
        self.save()

    def __str__(self):
        return f'{self.title}: {self.text}'

    # def get_absolute_url(self):  # new
    #     return reverse('PostForm', args=[str(self.id)])

# class PostCategory (models.Model):
#     postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
#     categoryTrough = models.ForeignKey(Category, on_delete=models.CASCADE)

class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()
    def dislike(self):
        self.rating -= 1
        self.save()
    def preview(self):
        return self.text[0:123] + '...'


class Subscription(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )

project/templates/article.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
<!-- Подключаем новый файл с нашим тегом -->
{% load custom_tags %}


<!-- Название у нас будет Product -->
{% block title %}
Работаем для вас 24 на 7
{% endblock title %}


<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}


   <h1>новость</h1>
   <hr>
   <hr>
   {% if Article %}
       <table>
           <tr>
               <td>Дата</td>
               <td>Название</td>
               <td>Описание</td>
               <td>Рейтинг</td>
           </tr>

           <!-- Для каждого товара будете генерироваться новая строчка,
           т.е. новый HTML код, который указан в теле цикла.
           При этом сам цикл работает точно так же, как и в Python.
           product — переменная цикла, т.е. наш товар полученный из списка -->

           <tr>
               <!-- Не забываем, что переменные в шаблоне ничем не отличаются
                от переменных в Python. Здесь также можно получать доступ к
                полям объекта модели. Например, здесь мы выводим имя,
                в следующем столбце описание, и т.д.  -->
               <td>{{ Article.dateCreation }}</td>
               <td>{{ Article.title|truncatewords:2|censor }}</td>
               <td>{{ Article.text|truncatechars:21|censor }}</td>
               <td>{{ Article.rating }}</td>
           </tr>


       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}




{{ post_detail }}
{% endblock content %}

project/templates/category.html
    <!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

<!-- Название у нас будет products -->
{% block title %}
Products
{% endblock title %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
<h1>Все товары</h1>
{{ product }}
{% endblock content %}

project/templates/comment.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}


<!-- Название у нас будет Product -->
{% block title %}
Post
{% endblock title %}




<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
<h1>{{ comment.text }}</h1>
{% endblock content %}

project/templates/post.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
<!-- Подключаем новый файл с нашим тегом -->
{% load custom_tags %}


<!-- Название у нас будет Product -->
{% block title %}
Работаем для вас 24 на 7
{% endblock title %}


<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
<h3>{{ time_now|date:'M d Y' }}</h3>

<h1>Все новости</h1>
{# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
<form action="" method="get">
    {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
    {{ filterset.form.as_p }}
    {# Добавим кнопку отправки данных формы #}
    <input type="submit" value="show"/>
</form>

<hr>

{# Теперь будем проверять не request.user.is_authenticated, а конкретные права #}
{% if perms.news.add_post %}
<a href="{% url 'post_create' %}">Добавить новость</a>
{% endif %}

{% if posts %}
<table>
    <tr>
        <td>Дата</td>
        <td>Название</td>
        <td>Описание</td>
        <td>Рейтинг</td>
        {# Условие получается составным. #}
        {% if perms.news.change_post or perms.news.delete_post %}
        <td>Действия</td>
        {% endif %}
    </tr>

    <!-- Для каждого товара будете генерироваться новая строчка,
    т.е. новый HTML код, который указан в теле цикла.
    При этом сам цикл работает точно так же, как и в Python.
    product — переменная цикла, т.е. наш товар полученный из списка -->
    {% for i in posts %}
    <tr>
        <!-- Не забываем, что переменные в шаблоне ничем не отличаются
         от переменных в Python. Здесь также можно получать доступ к
         полям объекта модели. Например, здесь мы выводим имя,
         в следующем столбце описание, и т.д.  -->
        <td>{{ i.dateCreation }}</td>
        <td>{{ i.title|truncatewords:2|censor }}</td>
        <td>{{ i.text|truncatechars:21|censor }}</td>
        <td>{{ i.rating }}</td>

        <td>
            {# А здесь доступ для каждой ссылки теперь будем проверять отдельно #}
            {% if perms.news.change_post %}
            <a href="{% url 'post_update' i.id %}">Изменить</a>
            {% endif %}
            {% if perms.news.delete_post %}
            <a href="{% url 'post_delete' i.id %}">Удалить</a>
            {% endif %}
        </td>

    </tr>
    {% endfor %}

</table>
{% else %}
<h2>Новостей нет!</h2>
{% endif %}

{# Добавляем пагинацию на страницу #}

{# Информация о предыдущих страницах #}
{% if page_obj.has_previous %}
<a href="?page=1">1</a>
{% if page_obj.previous_page_number != 1 %}
...
<a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
{% endif %}
{% endif %}

{# Информация о текущей странице #}
{{ page_obj.number }}

{# Информация о следующих страницах #}
{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
{% if paginator.num_pages != page_obj.next_page_number %}
...
<a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
{% endif %}
{% endif %}


{{ post_detail }}
{% endblock content %}

project/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление товара</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.name }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

project/templates/product_edit.html
{% extends 'flatpages/default.html'%}

{% block content %}

<h1>Все новости</h1>
<hr>
<form action="" method="post" >
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save" />
</form>

{% endblock content %}

project/templates/search.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
<!-- Подключаем новый файл с нашим тегом -->
{% load custom_tags %}


<!-- Название у нас будет Product -->
{% block title %}
Работаем для вас 24 на 7
{% endblock title %}


<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}


   <h1>Все новости</h1>
    <form action="" method="get" >
        {{ filterset.form.non_field_errors }}

        {{ filterset.form.title__icontains.errors }}
        <label for="{{ filterset.form.title__icontains.id_for_label }}">Search</label>
        <input
            id="{{ filterset.form.title__icontains.id }}"
            name="{{ filterset.form.title__icontains.name }}"
            value="{{ filterset.form.title__icontains.value }}"
            class="form-control"
        >
        <input type="submit" class="mt-3 btn-primary" value="Найти" />
    </form>

   <hr>
   {% if search %}
       <table>
           <tr>
               <td>Дата</td>
               <td>Название</td>
               <td>Описание</td>
               <td>Рейтинг</td>
           </tr>

           <!-- Для каждого товара будете генерироваться новая строчка,
           т.е. новый HTML код, который указан в теле цикла.
           При этом сам цикл работает точно так же, как и в Python.
           product — переменная цикла, т.е. наш товар полученный из списка -->
           {% for i in search %}
           <tr>
               <!-- Не забываем, что переменные в шаблоне ничем не отличаются
                от переменных в Python. Здесь также можно получать доступ к
                полям объекта модели. Например, здесь мы выводим имя,
                в следующем столбце описание, и т.д.  -->
               <td>{{ i.dateCreation }}</td>
               <td>{{ i.title|truncatewords:2|censor }}</td>
               <td>{{ i.text|truncatechars:21|censor }}</td>
               <td>{{ i.rating }}</td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}





{{ post_detail }}
{% endblock content %}

project/templates/subscribe.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <h1 class="text-center">{{ message }}ff category f</h1>
{% endblock content %}

project/templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}